version: '3.8'

services:
  patient_service:
    build: ./patient-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    container_name: patient_service
    volumes:
      - ./patient-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://patient_db_username:patient_db_password@patient_db/patient_db_dev
      - DRUG_SERVICE_HOST_URL=http://drug_service:8000/api/v1/drugs
    depends_on:
      - patient_db

  patient_db:
    image: postgres:13.0-alpine
    container_name: patient_db
    volumes:
      - postgres_data_patient:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=patient_db_username
      - POSTGRES_PASSWORD=patient_db_password
      - POSTGRES_DB=patient_db_dev

  drug_service:
    build: ./drugs-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    container_name: drug_service
    volumes:
      - ./drugs-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://drug_db_username:drug_db_password@drug_db/drug_db_dev
    depends_on:
      - drug_db

  drug_db:
    image: postgres:13.0-alpine
    container_name: drug_db
    volumes:
      - postgres_data_drug:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=drug_db_username
      - POSTGRES_PASSWORD=drug_db_password
      - POSTGRES_DB=drug_db_dev

  nginx:
    image: nginx:1.19
    links:
      - drug_service
      - patient_service
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=192.168.65.2
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data_patient:
  postgres_data_drug: